### ISSUE TITLE
Can't set a date for one off goals

### ISSUE THREAD

**Issue by KatCormack** [BuddyApp/frontend#10]
I can select a one off goal and set the time but not the date

![screenshot 2015-01-06 16 40 15](https://cloud.githubusercontent.com/assets/10165855/5631992/ec1321e6-95c2-11e4-84b0-c955e90b79aa.png)

**Comment by omarqureshi** [comment]
Fixed in 889f7c4, problem was that we had blindly copied and pasted over calendar code from the reschedule dialog
