### ISSUE TITLE
Can't set new goals

### ISSUE THREAD

**Issue by KatCormack** [BuddyApp/frontend#14]
As a clinician, log into a service user's account and try to set them a new goal 
Write new goal
Click "Add goal"
Kicked back out to diary, goal not set

**Comment by omarqureshi** [comment]
angular.js:8445 GET http://buddyapp.local/api/v1/service_users/newGoalSubmit().json 404 (Not Found)
angular.js:8445 XHR finished loading: GET "http://buddyapp.local/api/v1/service_users/newGoalSubmit().json".
angular.js:8445 GET http://buddyapp.local/api/v1/sessions.json?user_id=newGoalSubmit() 404 (Not Found)
angular.js:8445 GET http://buddyapp.local/api/v1/service_users/newGoalSubmit()/goals.json 404 (Not Found)

the id is VERY wrong.

**Comment by omarqureshi** [comment]
Functionally, this is working - still looks terrible though!
