### ISSUE TITLE
Login placeholders don't work on IE

### ISSUE THREAD

**Issue by KatCormack** [BuddyApp/frontend#22]
![screenshot 2015-02-04 14 08 44](https://cloud.githubusercontent.com/assets/10165855/6041767/761a962e-ac77-11e4-810a-c32cb48dbb71.png)

On IE you can't see the words "email address or phone number" and "password" which made it a bit confusing for clinicians i met yesterday who were logging on for the first time

**Comment by omarqureshi** [comment]
Added a directive with the placeholder attribute
